name: Generate APK & AAB Release
env:
  main_project_module: app

on:
  push:
    branches:
      - 'release/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE }}
        run: |
          mkdir -p app/keystore
          echo "$ENCODED_STRING" | base64 -di > app/keystore/your_keystore.jks

      - name: Set keystore file permissions
        run: chmod 600 app/keystore/your_keystore.jks

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Clean Gradle Build
        run: ./gradlew clean

      - name: Build release APK and AAB - ${{ env.main_project_module }} module
        run: |
          ./gradlew :${{ env.main_project_module }}:assembleRelease
          ./gradlew :${{ env.main_project_module }}:bundleRelease
        env:
          SIGNING_STORE_FILE: keystore/your_keystore.jks
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Verify APK and AAB existence
        run: |
          test -f app/build/outputs/apk/release/app-release.apk
          test -f app/build/outputs/bundle/release/app-release.aab

      - name: Upload APK and AAB to Github Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: |
            app/build/outputs/apk/release/app-release.apk
            app/build/outputs/bundle/release/app-release.aab

      - name: Create release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
          files: |
            app/build/outputs/apk/release/app-release.apk
            app/build/outputs/bundle/release/app-release.aab
          fail_on_unmatched_files: true
